export const SORT_CRITERIA_CHANGE = 'SORT_CRITERIA_CHANGE';

export const SEARCH_CRITERIA_CHANGE = 'SEARCH_CRITERIA_CHANGE';
export const SEARCH_STRING_CHANGE = 'SEARCH_STRING_CHANGE';

export const GET_RESULTS = 'GET_RESULTS';

export const FILM_OPENED = 'FILM_OPENED';
export const FILM_CLOSED = 'FILM_CLOSED';
