export const FILM_OPEN = 'FILM_OPEN';
export const FILM_CLOSE = 'FILM_CLOSE';

export const SORT_CRITERIA_CHANGE = 'SORT_CRITERIA_CHANGE';

export const SEARCH_CRITERIA_CHANGE = 'SEARCH_CRITERIA_CHANGE';
export const SEARCH_STRING_CHANGE = 'SEARCH_STRING_CHANGE';

export const RESULTS_UPDATE = 'RESULTS_UPDATE';

export const FETCH_DATA_BEGIN   = 'FETCH_DATA_BEGIN';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';


